require('dotenv').config();
var TelegramBot = require('node-telegram-bot-api');
var Anthropic = require('@anthropic-ai/sdk');
var https = require('https');

var telegramToken = process.env.TELEGRAM_BOT_TOKEN;
var anthropicKey = process.env.ANTHROPIC_API_KEY;
var githubToken = process.env.GITHUB_TOKEN;
var githubUser = process.env.GITHUB_USERNAME;
var railwayToken = process.env.RAILWAY_TOKEN;
var allowedUsers = (process.env.ALLOWED_USER_IDS || '').split(',').map(function(id) { return parseInt(id.trim()); });
var model = process.env.CLAUDE_MODEL || 'claude-sonnet-4-20250514';

if (!telegramToken) { console.error('Thieu TELEGRAM_BOT_TOKEN'); process.exit(1); }
if (!anthropicKey) { console.error('Thieu ANTHROPIC_API_KEY'); process.exit(1); }

var bot = new TelegramBot(telegramToken, { polling: true });
var claude = new Anthropic({ apiKey: anthropicKey });
var conversations = {};
var pendingBuilds = {};

var SYSTEM_PROMPT = 'Ban la AI Agent Coder chuyen dung cho Gom su Nam Viet. Ban la Senior Full-stack Developer. Viet code thuc te, chay duoc ngay. Tra loi bang tieng Viet, chuyen gia, thang than.';

var BUILD_PROMPT = 'Ban la AI Agent Coder. Khi nhan yeu cau tao ung dung, hay tra loi DUNG DINH DANG SAU (khong duoc sai):\n\n---FILES_START---\n===FILE: ten-file.js===\nnoi dung file\n===FILE: package.json===\nnoi dung file\n===FILE: README.md===\nnoi dung file\n---FILES_END---\n\nSau do viet tom tat ngan ve ung dung (2-3 dong).\n\nQuy tac:\n- Tao day du cac file can thiet de ung dung chay duoc\n- package.json PHAI co script start\n- README.md co huong dan cai dat\n- Code co comment tieng Viet\n- Boi canh: Gom su Nam Viet, 23 nhan vien, san pham gom su (hu gao, luc binh, mai binh, gom qua tang), kenh ban: gomsunamviet.vn, TikTok Shop, Shopee';

function isAllowed(userId) {
  if (allowedUsers.length === 1 && isNaN(allowedUsers[0])) return true;
  return allowedUsers.indexOf(userId) !== -1;
}

function getHistory(userId) {
  if (!conversations[userId]) conversations[userId] = [];
  return conversations[userId];
}

function addToHistory(userId, role, content) {
  var history = getHistory(userId);
  history.push({ role: role, content: content });
  while (history.length > 40) history.shift();
}

function splitMessage(text) {
  if (text.length <= 4000) return [text];
  var parts = [];
  var remaining = text;
  while (remaining.length > 0) {
    if (remaining.length <= 4000) { parts.push(remaining); break; }
    var cut = remaining.lastIndexOf('\n\n', 4000);
    if (cut === -1 || cut < 1200) cut = remaining.lastIndexOf('\n', 4000);
    if (cut === -1 || cut < 1200) cut = 4000;
    parts.push(remaining.substring(0, cut));
    remaining = remaining.substring(cut).trimStart();
  }
  return parts;
}

function sendLong(chatId, text) {
  var parts = splitMessage(text);
  var i = 0;
  function sendNext() {
    if (i >= parts.length) return;
    var part = parts[i];
    i++;
    bot.sendMessage(chatId, part, { parse_mode: 'Markdown', disable_web_page_preview: true })
      .catch(function() { return bot.sendMessage(chatId, part); })
      .catch(function(e) { console.error(e.message); })
      .then(function() { setTimeout(sendNext, 300); });
  }
  sendNext();
}

function githubAPI(method, path, data) {
  return new Promise(function(resolve, reject) {
    var body = data ? JSON.stringify(data) : '';
    var options = {
      hostname: 'api.github.com',
      path: path,
      method: method,
      headers: {
        'Authorization': 'token ' + githubToken,
        'User-Agent': 'namviet-bot',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body)
      }
    };
    var req = https.request(options, function(res) {
      var chunks = [];
      res.on('data', function(c) { chunks.push(c); });
      res.on('end', function() {
        var text = Buffer.concat(chunks).toString();
        try { resolve(JSON.parse(text)); } catch(e) { resolve(text); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

function createRepo(name) {
  return githubAPI('POST', '/user/repos', {
    name: name,
    description: 'Auto-generated by AI Agent Coder - Gom su Nam Viet',
    auto_init: true
  });
}

function pushFile(repo, filePath, content, message) {
  var encoded = Buffer.from(content).toString('base64');
  return githubAPI('PUT', '/repos/' + githubUser + '/' + repo + '/contents/' + filePath, {
    message: message || 'Add ' + filePath,
    content: encoded
  });
}

function railwayAPI(query, variables) {
  return new Promise(function(resolve, reject) {
    var body = JSON.stringify({ query: query, variables: variables || {} });
    var options = {
      hostname: 'backboard.railway.app',
      path: '/graphql/v2',
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + railwayToken,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body)
      }
    };
    var req = https.request(options, function(res) {
      var chunks = [];
      res.on('data', function(c) { chunks.push(c); });
      res.on('end', function() {
        var text = Buffer.concat(chunks).toString();
        try { resolve(JSON.parse(text)); } catch(e) { resolve(text); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function deployToRailway(repoName) {
  return railwayAPI(
    'mutation($input: ProjectCreateInput!) { projectCreate(input: $input) { id name } }',
    { input: { name: repoName } }
  ).then(function(result) {
    if (!result.data || !result.data.projectCreate) {
      throw new Error('Khong tao duoc project: ' + JSON.stringify(result));
    }
    var projectId = result.data.projectCreate.id;
    console.log('Railway project: ' + projectId);

    return railwayAPI(
      'query($id: String!) { project(id: $id) { environments { edges { node { id name } } } } }',
      { id: projectId }
    ).then(function(envResult) {
      var envId = '';
      if (envResult.data && envResult.data.project && envResult.data.project.environments) {
        var edges = envResult.data.project.environments.edges;
        if (edges.length > 0) envId = edges[0].node.id;
      }

      return railwayAPI(
        'mutation($input: ServiceCreateInput!) { serviceCreate(input: $input) { id name } }',
        { input: { projectId: projectId, name: repoName, source: { repo: githubUser + '/' + repoName } } }
      ).then(function(svcResult) {
        if (!svcResult.data || !svcResult.data.serviceCreate) {
          throw new Error('Khong tao duoc service: ' + JSON.stringify(svcResult));
        }
        console.log('Railway service: ' + svcResult.data.serviceCreate.id);
        return {
          projectId: projectId,
          url: 'https://railway.app/project/' + projectId
        };
      });
    });
  });
}

function parseFiles(text) {
  var files = [];
  var startTag = '---FILES_START---';
  var endTag = '---FILES_END---';
  var startIdx = text.indexOf(startTag);
  var endIdx = text.indexOf(endTag);
  if (startIdx === -1 || endIdx === -1) return files;
  var block = text.substring(startIdx + startTag.length, endIdx);
  var parts = block.split('===FILE: ');
  for (var i = 1; i < parts.length; i++) {
    var eqIdx = parts[i].indexOf('===');
    if (eqIdx === -1) continue;
    var filename = parts[i].substring(0, eqIdx).trim();
    var content = parts[i].substring(eqIdx + 3).trim();
    if (filename && content) {
      files.push({ name: filename, content: content });
    }
  }
  return files;
}

function getSummary(text) {
  var endTag = '---FILES_END---';
  var idx = text.indexOf(endTag);
  if (idx === -1) return 'Ung dung da duoc tao.';
  return text.substring(idx + endTag.length).trim() || 'Ung dung da duoc tao.';
}

bot.onText(/\/start/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  bot.sendMessage(msg.chat.id,
    'AI Agent Coder v3 - Gom su Nam Viet\n\n' +
    'LENH:\n' +
    '/build [yeu cau] - Code + Push GitHub + Auto Deploy Railway\n' +
    '/reset - Xoa lich su\n' +
    '/status - Trang thai\n\n' +
    'VD: /build Tao chatbot Facebook tu van gom su\n' +
    'VD: /build Tao dashboard quan ly kho React\n\n' +
    'Hoac gui tin nhan de hoi dap.'
  );
});

bot.onText(/\/reset/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  delete conversations[msg.from.id];
  bot.sendMessage(msg.chat.id, 'Da xoa lich su.');
});

bot.onText(/\/status/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  var h = getHistory(msg.from.id);
  bot.sendMessage(msg.chat.id,
    'Model: ' + model +
    '\nLich su: ' + h.length +
    '\nGitHub: ' + githubUser +
    '\nRailway: ' + (railwayToken ? 'OK' : 'Chua cau hinh') +
    '\nUser: ' + msg.from.id
  );
});

bot.onText(/\/build (.+)/, function(msg, match) {
  if (!isAllowed(msg.from.id)) return;
  var request = match[1];
  var chatId = msg.chat.id;
  var userId = msg.from.id;

  if (!githubToken || !githubUser) {
    bot.sendMessage(chatId, 'Chua cau hinh GITHUB_TOKEN va GITHUB_USERNAME.');
    return;
  }

  bot.sendMessage(chatId, 'Dang code ung dung:\n\n"' + request + '"\n\nDoi 30-60 giay...');
  bot.sendChatAction(chatId, 'typing');

  claude.messages.create({
    model: model,
    max_tokens: 8192,
    system: BUILD_PROMPT,
    messages: [{ role: 'user', content: request }]
  }).then(function(res) {
    var reply = '';
    for (var j = 0; j < res.content.length; j++) {
      if (res.content[j].type === 'text') reply += res.content[j].text;
    }
    var files = parseFiles(reply);
    var summary = getSummary(reply);

    if (files.length === 0) {
      bot.sendMessage(chatId, 'Khong tao duoc file. Thu lai cu the hon.');
      return;
    }

    var fileList = '';
    for (var k = 0; k < files.length; k++) {
      fileList += '  ' + files[k].name + '\n';
    }

    var repoName = request.toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 40);
    if (!repoName) repoName = 'ai-project-' + Date.now();

    pendingBuilds[userId] = {
      files: files,
      repoName: repoName,
      summary: summary,
      request: request
    };

    bot.sendMessage(chatId,
      'DA CODE XONG!\n\n' +
      'Files (' + files.length + '):\n' + fileList + '\n' +
      summary + '\n\n' +
      'Bam DUYET de tu dong:\n1. Tao repo GitHub\n2. Push code\n3. Deploy Railway',
      {
        reply_markup: {
          inline_keyboard: [[
            { text: 'DUYET - Build & Deploy', callback_data: 'approve_build' },
            { text: 'HUY', callback_data: 'reject_build' }
          ]]
        }
      }
    );
  }).catch(function(err) {
    console.error(err.message);
    bot.sendMessage(chatId, 'Loi: ' + err.message);
  });
});

bot.on('callback_query', function(query) {
  var userId = query.from.id;
  var chatId = query.message.chat.id;

  if (query.data === 'approve_build') {
    var build = pendingBuilds[userId];
    if (!build) {
      bot.answerCallbackQuery(query.id, { text: 'Khong co build nao dang cho.' });
      return;
    }

    bot.answerCallbackQuery(query.id, { text: 'Dang xu ly...' });
    bot.sendMessage(chatId, 'Buoc 1/3: Tao repo GitHub...');

    createRepo(build.repoName).then(function(repo) {
      if (repo.message && repo.message.indexOf('already exists') !== -1) {
        build.repoName = build.repoName + '-' + Date.now();
        return createRepo(build.repoName);
      }
      return repo;
    }).then(function() {
      bot.sendMessage(chatId, 'Buoc 2/3: Push ' + build.files.length + ' files...');

      var idx = 0;
      function pushNext() {
        if (idx >= build.files.length) {
          var repoUrl = 'https://github.com/' + githubUser + '/' + build.repoName;

          if (railwayToken) {
            bot.sendMessage(chatId, 'Buoc 3/3: Deploy len Railway...');
            deployToRailway(build.repoName).then(function(result) {
              bot.sendMessage(chatId,
                'HOAN THANH!\n\n' +
                'GitHub: ' + repoUrl + '\n' +
                'Railway: ' + result.url + '\n\n' +
                'App dang duoc deploy. Vao Railway link tren de xem trang thai va them Variables neu can.'
              );
              delete pendingBuilds[userId];
            }).catch(function(err) {
              console.error('Railway error: ' + err.message);
              bot.sendMessage(chatId,
                'Da push code len GitHub!\n\n' +
                'GitHub: ' + repoUrl + '\n\n' +
                'Railway auto-deploy loi: ' + err.message + '\n' +
                'Thu vao Railway > New > chon repo "' + build.repoName + '"'
              );
              delete pendingBuilds[userId];
            });
          } else {
            bot.sendMessage(chatId,
              'HOAN THANH!\n\nGitHub: ' + repoUrl + '\n\nVao Railway > New > chon repo "' + build.repoName + '" de deploy.'
            );
            delete pendingBuilds[userId];
          }
          return;
        }
        var file = build.files[idx];
        idx++;
        pushFile(build.repoName, file.name, file.content, 'Add ' + file.name)
          .then(function() {
            console.log('Pushed: ' + file.name);
            setTimeout(pushNext, 1000);
          })
          .catch(function(err) {
            console.error('Push error: ' + err.message);
            setTimeout(pushNext, 1000);
          });
      }
      pushNext();
    }).catch(function(err) {
      console.error('Repo error: ' + err.message);
      bot.sendMessage(chatId, 'Loi tao repo: ' + err.message);
    });

  } else if (query.data === 'reject_build') {
    delete pendingBuilds[userId];
    bot.answerCallbackQuery(query.id, { text: 'Da huy.' });
    bot.sendMessage(chatId, 'Da huy.');
  }
});

bot.on('message', function(msg) {
  if (msg.text && msg.text.charAt(0) === '/') return;
  if (!isAllowed(msg.from.id)) return;
  if (!msg.text || !msg.text.trim()) return;

  bot.sendChatAction(msg.chat.id, 'typing');
  addToHistory(msg.from.id, 'user', msg.text);

  claude.messages.create({
    model: model,
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: getHistory(msg.from.id)
  }).then(function(res) {
    var reply = '';
    for (var j = 0; j < res.content.length; j++) {
      if (res.content[j].type === 'text') reply += res.content[j].text;
    }
    addToHistory(msg.from.id, 'assistant', reply);
    sendLong(msg.chat.id, reply);
    console.log('User:' + msg.from.id + ' In:' + res.usage.input_tokens + ' Out:' + res.usage.output_tokens);
  }).catch(function(err) {
    console.error(err.message);
    var e = 'Co loi xay ra.';
    if (err.status === 429) e = 'Rate limit. Doi 30 giay.';
    else if (err.status === 401) e = 'API Key sai.';
    else if (err.status === 400) { e = 'Context qua dai. Dung /reset'; delete conversations[msg.from.id]; }
    bot.sendMessage(msg.chat.id, e);
  });
});

console.log('AI Agent Coder v3 dang chay... Model: ' + model + ' | GitHub: ' + githubUser + ' | Railway: ' + (railwayToken ? 'OK' : 'N/A'));
