require('dotenv').config();
var TelegramBot = require('node-telegram-bot-api');
var Anthropic = require('@anthropic-ai/sdk');
var https = require('https');

var telegramToken = process.env.TELEGRAM_BOT_TOKEN;
var anthropicKey = process.env.ANTHROPIC_API_KEY;
var githubToken = process.env.GITHUB_TOKEN;
var githubUser = process.env.GITHUB_USERNAME;
var allowedUsers = (process.env.ALLOWED_USER_IDS || '').split(',').map(function(id) { return parseInt(id.trim()); });
var model = process.env.CLAUDE_MODEL || 'claude-sonnet-4-20250514';

if (!telegramToken) { console.error('Thieu TELEGRAM_BOT_TOKEN'); process.exit(1); }
if (!anthropicKey) { console.error('Thieu ANTHROPIC_API_KEY'); process.exit(1); }

var bot = new TelegramBot(telegramToken, { polling: true });
var claude = new Anthropic({ apiKey: anthropicKey });
var conversations = {};
var pendingBuilds = {};

var SYSTEM_PROMPT = 'Ban la AI Agent Coder chuyen dung cho Gom su Nam Viet. Ban la Senior Full-stack Developer. Viet code thuc te, chay duoc ngay. Tra loi bang tieng Viet, chuyen gia, thang than.';

var BUILD_PROMPT = 'Ban la AI Agent Coder. Khi nhan yeu cau tao ung dung, hay tra loi DUNG DINH DANG SAU (khong duoc sai):\n\n---FILES_START---\n===FILE: ten-file.js===\nnoi dung file\n===FILE: package.json===\nnoi dung file\n===FILE: README.md===\nnoi dung file\n---FILES_END---\n\nSau do viet tom tat ngan ve ung dung (2-3 dong).\n\nQuy tac:\n- Tao day du cac file can thiet de ung dung chay duoc\n- package.json PHAI co script start\n- README.md co huong dan cai dat\n- Code co comment tieng Viet\n- Boi canh: Gom su Nam Viet, 23 nhan vien, san pham gom su (hu gao, luc binh, mai binh, gom qua tang), kenh ban: gomsunamviet.vn, TikTok Shop, Shopee';

function isAllowed(userId) {
  if (allowedUsers.length === 1 && isNaN(allowedUsers[0])) return true;
  return allowedUsers.indexOf(userId) !== -1;
}

function getHistory(userId) {
  if (!conversations[userId]) conversations[userId] = [];
  return conversations[userId];
}

function addToHistory(userId, role, content) {
  var history = getHistory(userId);
  history.push({ role: role, content: content });
  while (history.length > 40) history.shift();
}

function splitMessage(text) {
  if (text.length <= 4000) return [text];
  var parts = [];
  var remaining = text;
  while (remaining.length > 0) {
    if (remaining.length <= 4000) { parts.push(remaining); break; }
    var cut = remaining.lastIndexOf('\n\n', 4000);
    if (cut === -1 || cut < 1200) cut = remaining.lastIndexOf('\n', 4000);
    if (cut === -1 || cut < 1200) cut = 4000;
    parts.push(remaining.substring(0, cut));
    remaining = remaining.substring(cut).trimStart();
  }
  return parts;
}

function sendLong(chatId, text) {
  var parts = splitMessage(text);
  var i = 0;
  function sendNext() {
    if (i >= parts.length) return;
    var part = parts[i];
    i++;
    bot.sendMessage(chatId, part, { parse_mode: 'Markdown', disable_web_page_preview: true })
      .catch(function() { return bot.sendMessage(chatId, part); })
      .catch(function(e) { console.error(e.message); })
      .then(function() { setTimeout(sendNext, 300); });
  }
  sendNext();
}

// --- GITHUB API ---
function githubAPI(method, path, data) {
  return new Promise(function(resolve, reject) {
    var body = data ? JSON.stringify(data) : '';
    var options = {
      hostname: 'api.github.com',
      path: path,
      method: method,
      headers: {
        'Authorization': 'token ' + githubToken,
        'User-Agent': 'namviet-bot',
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body)
      }
    };
    var req = https.request(options, function(res) {
      var chunks = [];
      res.on('data', function(c) { chunks.push(c); });
      res.on('end', function() {
        var text = Buffer.concat(chunks).toString();
        try { resolve(JSON.parse(text)); } catch(e) { resolve(text); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

function createRepo(name) {
  return githubAPI('POST', '/user/repos', {
    name: name,
    description: 'Auto-generated by AI Agent Coder - Gom su Nam Viet',
    auto_init: true
  });
}

function pushFile(repo, filePath, content, message) {
  var encoded = Buffer.from(content).toString('base64');
  return githubAPI('PUT', '/repos/' + githubUser + '/' + repo + '/contents/' + filePath, {
    message: message || 'Add ' + filePath,
    content: encoded
  });
}

// --- PARSE FILES TU CLAUDE RESPONSE ---
function parseFiles(text) {
  var files = [];
  var startTag = '---FILES_START---';
  var endTag = '---FILES_END---';
  var startIdx = text.indexOf(startTag);
  var endIdx = text.indexOf(endTag);
  if (startIdx === -1 || endIdx === -1) return files;
  var block = text.substring(startIdx + startTag.length, endIdx);
  var parts = block.split('===FILE: ');
  for (var i = 1; i < parts.length; i++) {
    var eqIdx = parts[i].indexOf('===');
    if (eqIdx === -1) continue;
    var filename = parts[i].substring(0, eqIdx).trim();
    var content = parts[i].substring(eqIdx + 3).trim();
    if (filename && content) {
      files.push({ name: filename, content: content });
    }
  }
  return files;
}

function getSummary(text) {
  var endTag = '---FILES_END---';
  var idx = text.indexOf(endTag);
  if (idx === -1) return 'Ung dung da duoc tao.';
  return text.substring(idx + endTag.length).trim() || 'Ung dung da duoc tao.';
}

// --- COMMANDS ---
bot.onText(/\/start/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  bot.sendMessage(msg.chat.id,
    'AI Agent Coder - Gom su Nam Viet\n\n' +
    'LENH:\n' +
    '/build [yeu cau] - Tao ung dung moi (AI code + tu push GitHub)\n' +
    '/chat [cau hoi] - Hoi dap, tu van code\n' +
    '/reset - Xoa lich su\n' +
    '/status - Trang thai\n\n' +
    'VD: /build Tao chatbot Facebook Messenger tu van gom su\n' +
    'VD: /build Tao dashboard quan ly kho React\n\n' +
    'Hoac gui truc tiep cau hoi de chat binh thuong.'
  );
});

bot.onText(/\/reset/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  delete conversations[msg.from.id];
  bot.sendMessage(msg.chat.id, 'Da xoa lich su.');
});

bot.onText(/\/status/, function(msg) {
  if (!isAllowed(msg.from.id)) return;
  var h = getHistory(msg.from.id);
  bot.sendMessage(msg.chat.id, 'Model: ' + model + '\nLich su: ' + h.length + '\nGitHub: ' + githubUser + '\nUser: ' + msg.from.id);
});

// --- /build COMMAND ---
bot.onText(/\/build (.+)/, function(msg, match) {
  if (!isAllowed(msg.from.id)) return;
  var request = match[1];
  var chatId = msg.chat.id;
  var userId = msg.from.id;

  if (!githubToken || !githubUser) {
    bot.sendMessage(chatId, 'Chua cau hinh GITHUB_TOKEN va GITHUB_USERNAME.');
    return;
  }

  bot.sendMessage(chatId, '🔍 Dang phan tich yeu cau:\n\n"' + request + '"\n\nDoi 30-60 giay...');
  bot.sendChatAction(chatId, 'typing');

  claude.messages.create({
    model: model,
    max_tokens: 8192,
    system: BUILD_PROMPT,
    messages: [{ role: 'user', content: request }]
  }).then(function(res) {
    var reply = '';
    for (var j = 0; j < res.content.length; j++) {
      if (res.content[j].type === 'text') reply += res.content[j].text;
    }
    var files = parseFiles(reply);
    var summary = getSummary(reply);

    if (files.length === 0) {
      bot.sendMessage(chatId, 'Khong tao duoc file. Thu lai voi yeu cau cu the hon.');
      return;
    }

    var fileList = '';
    for (var k = 0; k < files.length; k++) {
      fileList += '  ' + files[k].name + '\n';
    }

    var repoName = request.toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 40);
    if (!repoName) repoName = 'ai-project-' + Date.now();

    pendingBuilds[userId] = {
      files: files,
      repoName: repoName,
      summary: summary,
      request: request
    };

    bot.sendMessage(chatId,
      '✅ DA CODE XONG!\n\n' +
      'Yeu cau: ' + request + '\n\n' +
      'Files (' + files.length + '):\n' + fileList + '\n' +
      'Repo: github.com/' + githubUser + '/' + repoName + '\n\n' +
      summary + '\n\n' +
      'Ban muon tao repo va deploy khong?',
      {
        reply_markup: {
          inline_keyboard: [[
            { text: '✅ DUYỆT - Push lên GitHub', callback_data: 'approve_build' },
            { text: '❌ HỦY', callback_data: 'reject_build' }
          ]]
        }
      }
    );

    console.log('Build ready: ' + files.length + ' files for ' + repoName);
  }).catch(function(err) {
    console.error(err.message);
    bot.sendMessage(chatId, 'Loi: ' + err.message);
  });
});

// --- APPROVE / REJECT ---
bot.on('callback_query', function(query) {
  var userId = query.from.id;
  var chatId = query.message.chat.id;

  if (query.data === 'approve_build') {
    var build = pendingBuilds[userId];
    if (!build) {
      bot.answerCallbackQuery(query.id, { text: 'Khong co build nao dang cho.' });
      return;
    }

    bot.answerCallbackQuery(query.id, { text: 'Dang tao repo...' });
    bot.sendMessage(chatId, '🚀 Dang tao repo va push code...');

    createRepo(build.repoName).then(function(repo) {
      if (repo.message && repo.message.indexOf('already exists') !== -1) {
        build.repoName = build.repoName + '-' + Date.now();
        return createRepo(build.repoName);
      }
      return repo;
    }).then(function() {
      // Push tung file, doi 1 giay giua moi file
      var idx = 0;
      function pushNext() {
        if (idx >= build.files.length) {
          var repoUrl = 'https://github.com/' + githubUser + '/' + build.repoName;
          bot.sendMessage(chatId,
            '✅ HOAN THANH!\n\n' +
            'Repo: ' + repoUrl + '\n\n' +
            'Da push ' + build.files.length + ' files.\n\n' +
            'Buoc tiep:\n' +
            '1. Vao Railway > New > GitHub Repo > chon "' + build.repoName + '"\n' +
            '2. Them Variables (neu can)\n' +
            '3. App tu dong chay!\n\n' +
            'Hoac gui /build de tao ung dung tiep.'
          );
          delete pendingBuilds[userId];
          return;
        }
        var file = build.files[idx];
        idx++;
        pushFile(build.repoName, file.name, file.content, 'Add ' + file.name)
          .then(function() {
            console.log('Pushed: ' + file.name);
            setTimeout(pushNext, 1000);
          })
          .catch(function(err) {
            console.error('Push error: ' + err.message);
            setTimeout(pushNext, 1000);
          });
      }
      pushNext();
    }).catch(function(err) {
      console.error('Repo error: ' + err.message);
      bot.sendMessage(chatId, 'Loi tao repo: ' + err.message);
    });

  } else if (query.data === 'reject_build') {
    delete pendingBuilds[userId];
    bot.answerCallbackQuery(query.id, { text: 'Da huy.' });
    bot.sendMessage(chatId, 'Da huy. Gui /build de thu lai.');
  }
});

// --- CHAT BINH THUONG ---
bot.on('message', function(msg) {
  if (msg.text && msg.text.charAt(0) === '/') return;
  if (!isAllowed(msg.from.id)) return;
  if (!msg.text || !msg.text.trim()) return;

  bot.sendChatAction(msg.chat.id, 'typing');
  addToHistory(msg.from.id, 'user', msg.text);

  claude.messages.create({
    model: model,
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: getHistory(msg.from.id)
  }).then(function(res) {
    var reply = '';
    for (var j = 0; j < res.content.length; j++) {
      if (res.content[j].type === 'text') reply += res.content[j].text;
    }
    addToHistory(msg.from.id, 'assistant', reply);
    sendLong(msg.chat.id, reply);
    console.log('User:' + msg.from.id + ' In:' + res.usage.input_tokens + ' Out:' + res.usage.output_tokens);
  }).catch(function(err) {
    console.error(err.message);
    var e = 'Co loi xay ra.';
    if (err.status === 429) e = 'Rate limit. Doi 30 giay.';
    else if (err.status === 401) e = 'API Key sai.';
    else if (err.status === 400) { e = 'Context qua dai. Dung /reset'; delete conversations[msg.from.id]; }
    bot.sendMessage(msg.chat.id, e);
  });
});

console.log('AI Agent Coder v2 dang chay... Model: ' + model + ' | GitHub: ' + githubUser);
```

Nhấn **Commit changes**. Sau đó quay lại **Railway** nhấn **Deploy**. Đợi 1-2 phút cho nó online, rồi thử gửi trên Telegram:
```
/build Tao chatbot Facebook Messenger tu van gom su cho khach hang
